

//alert('This is a  mtm6302-exercise-1. ');
// Emoji Data 😃👾👨🏼‍💻
const EmojiData = [
  //Data of 100 Differenct Emoji and their corresponding Unicode
  { emoji: '😀', hexadecimal: '1F600' },
  { emoji: '😂', hexadecimal: '1F602' },
  { emoji: '😃', hexadecimal: '1F603' },
  { emoji: '😄', hexadecimal: '1F604' },
  { emoji: '😅', hexadecimal: '1F605' },
  { emoji: '😆', hexadecimal: '1F606' },
  { emoji: '😇', hexadecimal: '1F607' },
  { emoji: '😈', hexadecimal: '1F608' },
  { emoji: '😉', hexadecimal: '1F609' },
  { emoji: '😊', hexadecimal: '1F60A' },
  { emoji: '😋', hexadecimal: '1F60B' },
  { emoji: '😌', hexadecimal: '1F60C' },
  { emoji: '😍', hexadecimal: '1F60D' },
  { emoji: '😎', hexadecimal: '1F60E' },
  { emoji: '😏', hexadecimal: '1F60F' },
  { emoji: '😐', hexadecimal: '1F610' },
  { emoji: '😑', hexadecimal: '1F611' },
  { emoji: '😒', hexadecimal: '1F612' },
  { emoji: '😓', hexadecimal: '1F613' },
  { emoji: '😔', hexadecimal: '1F614' },
  { emoji: '😕', hexadecimal: '1F615' },
  { emoji: '😖', hexadecimal: '1F616' },
  { emoji: '😗', hexadecimal: '1F617' },
  { emoji: '😘', hexadecimal: '1F618' },
  { emoji: '😙', hexadecimal: '1F619' },
  { emoji: '😚', hexadecimal: '1F61A' },
  { emoji: '😛', hexadecimal: '1F61B' },
  { emoji: '😜', hexadecimal: '1F61C' },
  { emoji: '😝', hexadecimal: '1F61D' },
  { emoji: '😞', hexadecimal: '1F61E' },
  { emoji: '😟', hexadecimal: '1F61F' },
  { emoji: '😠', hexadecimal: '1F620' },
  { emoji: '😡', hexadecimal: '1F621' },
  { emoji: '😢', hexadecimal: '1F622' },
  { emoji: '😣', hexadecimal: '1F623' },
  { emoji: '😤', hexadecimal: '1F624' },
  { emoji: '😥', hexadecimal: '1F625' },
  { emoji: '😦', hexadecimal: '1F626' },
  { emoji: '😧', hexadecimal: '1F627' },
  { emoji: '😨', hexadecimal: '1F628' },
  { emoji: '😩', hexadecimal: '1F629' },
  { emoji: '😪', hexadecimal: '1F62A' },
  { emoji: '😫', hexadecimal: '1F62B' },
  { emoji: '😬', hexadecimal: '1F62C' },
  { emoji: '😭', hexadecimal: '1F62D' },
  { emoji: '😮', hexadecimal: '1F62E' },
  { emoji: '😯', hexadecimal: '1F62F' },
  { emoji: '😰', hexadecimal: '1F630' },
  { emoji: '😱', hexadecimal: '1F631' },
  { emoji: '😲', hexadecimal: '1F632' },
  { emoji: '😳', hexadecimal: '1F633' },
  { emoji: '😴', hexadecimal: '1F634' },
  { emoji: '😵', hexadecimal: '1F635' },
  { emoji: '😶', hexadecimal: '1F636' },
  { emoji: '😷', hexadecimal: '1F637' },
  { emoji: '😸', hexadecimal: '1F638' },
  { emoji: '😹', hexadecimal: '1F639' },
  { emoji: '😺', hexadecimal: '1F63A' },
  { emoji: '😻', hexadecimal: '1F63B' },
  { emoji: '😼', hexadecimal: '1F63C' },
  { emoji: '😽', hexadecimal: '1F63D' },
  { emoji: '😾', hexadecimal: '1F63E' },
  { emoji: '😿', hexadecimal: '1F63F' },
  { emoji: '🙀', hexadecimal: '1F640' },
  { emoji: '🙁', hexadecimal: '1F641' },
  { emoji: '🙂', hexadecimal: '1F642' },
  { emoji: '🙃', hexadecimal: '1F643' },
  { emoji: '🙄', hexadecimal: '1F644' },
  { emoji: '🙅', hexadecimal: '1F645' },
  { emoji: '🙆', hexadecimal: '1F646' },
  { emoji: '🙇', hexadecimal: '1F647' },
  { emoji: '🙈', hexadecimal: '1F648' },
  { emoji: '🙉', hexadecimal: '1F649' },
  { emoji: '🙊', hexadecimal: '1F64A' },
  { emoji: '🙋', hexadecimal: '1F64B' },
  { emoji: '🙌', hexadecimal: '1F64C' },
  { emoji: '🙍', hexadecimal: '1F64D' },
  { emoji: '🙎', hexadecimal: '1F64E' },
  { emoji: '🙏', hexadecimal: '1F64F' },
  { emoji: '🚀', hexadecimal: '1F680' },
  { emoji: '🚁', hexadecimal: '1F681' },
  { emoji: '🚂', hexadecimal: '1F682' },
  { emoji: '🚃', hexadecimal: '1F683' },
  { emoji: '🚄', hexadecimal: '1F684' },
  { emoji: '🚅', hexadecimal: '1F685' },
  { emoji: '🚆', hexadecimal: '1F686' },
  { emoji: '🚇', hexadecimal: '1F687' },
  { emoji: '🚈', hexadecimal: '1F688' },
  { emoji: '🚉', hexadecimal: '1F689' },
  { emoji: '🚊', hexadecimal: '1F68A' },
  { emoji: '🚋', hexadecimal: '1F68B' },
  { emoji: '🚌', hexadecimal: '1F68C' },
  { emoji: '🚍', hexadecimal: '1F68D' },
  { emoji: '🚎', hexadecimal: '1F68E' },
  { emoji: '🚏', hexadecimal: '1F68F' },
  { emoji: '🚐', hexadecimal: '1F690' },
  { emoji: '🚑', hexadecimal: '1F691' },
  { emoji: '🚒', hexadecimal: '1F692' },
  { emoji: '🚓', hexadecimal: '1F693' },
  { emoji: '🚔', hexadecimal: '1F694' },
  { emoji: '🚕', hexadecimal: '1F695' },
  { emoji: '🚖', hexadecimal: '1F696' },
  { emoji: '🚗', hexadecimal: '1F697' },
  { emoji: '🚘', hexadecimal: '1F698' },
  { emoji: '🚙', hexadecimal: '1F699' },
  { emoji: '🚚', hexadecimal: '1F69A' },
  { emoji: '🚛', hexadecimal: '1F69B' },
  { emoji: '🚜', hexadecimal: '1F69C' },
  { emoji: '🚝', hexadecimal: '1F69D' },
  { emoji: '🚞', hexadecimal: '1F69E' },
  { emoji: '🚟', hexadecimal: '1F69F' },
  { emoji: '🚠', hexadecimal: '1F6A0' },
  { emoji: '🚡', hexadecimal: '1F6A1' },







];

const $list = document.getElementById('list');
for (let i = 0; i < EmojiData.length; i++) {
  $list.innerHTML += `<p>
  <span style="font-size: 5rem">${EmojiData[i].emoji}</span><br />
  <code>${EmojiData[i].hexadecimal}</code>
</p>`


}

console.log($list.innerHTML);